### ISSUE TITLE
Handle global NPM packages

### ISSUE THREAD

**Issue by rocky** [ConsenSys/truffle-security#129]
Right now we handle locally-install npm packages. But what if openZepplin is installed globally?

**Comment by tagomaru** [comment]
This concept was implemented at [this PR](https://github.com/ConsenSys/truffle-security/pull/123/files) which did not be merged.

**Comment by rocky** [comment]
So if we merge that, we are then good? Or does this need to be reworked?

**Comment by tagomaru** [comment]
No, we already merged another one. This is not compatible for that. I work on it at a later date.

**Comment by rocky** [comment]
The other thing to keep in mind is that if we use `truffle-resolve` things may change again. It might have to be worked into the NPM module instead of how it would be done now.

**Comment by tagomaru** [comment]
Yes, thanks, i know.
I think we should refer to that to handle npm and EthPM at the same time.

**Comment by tagomaru** [comment]
@rocky 
> Right now we handle locally-install npm packages. But what if openZepplin is installed globally?

According to my investigation, truffle itself does not support globally installed package.
So i think we do not have to resolve this.
I may send PR for supporting globally installed package to truffle-resolver itself at a later date.

**Comment by rocky** [comment]
Yes, building on truffle-resolver is the way to go.

**Comment by tagomaru** [comment]
yes i am closing this.
