### ISSUE TITLE
Add option to allow ignore of specific warnings or errors

### ISSUE THREAD

**Issue by caleteeter** [ConsenSys/truffle-security#136]
Provide the option to allow comments for ignoring specific warnings or errors.  Providing functionality similar to common linters would be ideal.

**Comment by rocky** [comment]
I think this should be covered by #116

**Comment by nbanmp** [comment]
Closing this issue, as it is covered by #116 (and the in progress PR #139).

If you think this should be reopened, please open it again with an explanation.

**Comment by willclarktech** [comment]
As far as I can see, #116 doesn't cover inline cases. Example use case: I have a base contract and a test contract which extends it. In the test contract I override a `private` state variable for testing purposes, which gives rise to this warning from the tool: 

```
23:4  warning  State variable shadows another state variable  SWC-119
```

I want to disable that check on that line, but not for the rest of the project (or even the rest of the file). This is common functionality for linters (eg eslint, solhint).
