### ISSUE TITLE
Is there a way to ignore given checks?

### ISSUE THREAD

**Issue by Ferparishuertas** [ConsenSys/truffle-security#147]
We are facing the following errors as verify result, and we want to skip it

/Users/fer/Documents/PERSONAL/IOBUILDERS/em-token/contracts/BalanceConverter.sol
  23:45  error  The binary exponentiation can overflow  SWC-1

``
    _newBalance = _legacyBalance.mul(10 ** uint256(ratio));

/Users/fer/Documents/PERSONAL/IOBUILDERS/em-token/contracts/TokenRegulatorService.sol
  218:16  error    The binary addition can overflow

``
  if (participants[_token][_from].value & PERM_SEND == 0) {
                return CHECK_ESEND;
            }

**Comment by rocky** [comment]
This is related to #116, but more work will be needed when that is doine if I understand this correctly

**Comment by daniyarchambylov** [comment]
@Ferparishuertas  Could you please verify whether passing `--swc-blacklist` works for you. PR #139 should resolve it. Thanks!
