### ISSUE TITLE
`truffle run verify` is not returning results

### ISSUE THREAD

**Issue by streichsbaer** [ConsenSys/truffle-security#155]
I don't get any results when running `truffle compile` and `truffle run verify` against the mythx-playground exercises (e.g exercise2). I have tried this on MacOS and in an Alpine docker container with the same results.

```Dockerfile
FROM node:10-alpine
RUN apk add nodejs npm git python make g++
RUN npm install -g npm \
    && npm install -g --unsafe-perm sabre-mythx \
    && npm install -g --unsafe-perm truffle truffle-security
```

The version numbers of `truffle` and `truffle-security` are:

```
$ truffle version
Truffle v5.0.10 (core: 5.0.10)
Solidity v0.5.0 (solc-js)
Node v10.13.0
Web3.js v1.0.0-beta.37
```

```
$ truffle run verify --version
truffle-security 1.3.1
api: v1.4.10, harvey: 0.0.16, hash: 62f6c16c62bf4bda87784715c172ac57, maestro: 1.2.5, maru: 0.4.0, mythril: 0.20.1, url: https://api.mythx.io
```

I have added the `plugins: [ "truffle-security" ]` into the truffle.js and truffle-config.js file and can compile the exercise2.

![image](https://user-images.githubusercontent.com/5006784/55287616-dc468e00-53dd-11e9-8d8d-f101add02610.png)

But when running `truffle run verify` then nothing happens:
![image](https://user-images.githubusercontent.com/5006784/55287624-f4b6a880-53dd-11e9-903f-4dda90aa1ee2.png)

Both `MYTHX_PASSWORD` and `MYTHX_ETH_ADDRESS` are set.

Any ideas what the issue could be?

**Comment by daniyarchambylov** [comment]
@streichsbaer I've used your Dockerfile and installed latest truffle-security. Everything works for me.
```
$ truffle version
Truffle v5.0.10 (core: 5.0.10)
Solidity v0.5.0 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37
```
```
$ truffle run verify --version
ruffle-security 1.3.2
api: v1.4.12, harvey: 0.0.16, hash: 115b0fbe157b85d76e68f16db11b8fd1, maestro: 1.2.6, maru: 0.4.2, mythril: 0.20.1, url: https://api.mythx.io
```
Complete output: https://gist.github.com/daniyarchambylov/e42932336285d0994fbdb7e7dd224c01

Can you try again and verify whether issue is fixed or not?

**Comment by streichsbaer** [comment]
Thanks @daniyarchambylov. Turns out it was an issue with permissions on my side.
Closing this issue.
