### ISSUE TITLE
False positive error swc 101 on pragma statement

### ISSUE THREAD

**Issue by elenadimitrova** [ConsenSys/truffle-security#204]
There is a SWC-101 error thrown at a pragma declaration for [this](https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/PatriciaTree/Bits.sol#L1) contract. Note that the error is thrown also on using a fixed pragma version, e.g. `pragma solidity 0.5.8;`

**Comment by nbanmp** [comment]
There is a fix in progress for this bug. It is almost to production.

**Comment by nbanmp** [comment]
Closing, as I believe this is resolved. Please reopen this if it is still an issue.

**Comment by area** [comment]
We are now seeing this on [this contract](https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/Resolver.sol), being reported as line 5, columns 15-27 and line 6 column 51 to line 7 column 13...
