### ISSUE TITLE
HTML report is not generated properly

### ISSUE THREAD

**Issue by PaulRBerg** [ConsenSys/truffle-security#213]
Titles still refer to "ESLint" and links point to their website:

```
<a href="https://eslint.org/docs/rules/SWC-120" target="_blank" rel="noopener noreferrer">SWC-120</a>
```

That should instead be:

```
<a href="https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-120" target="_blank" rel="noopener noreferrer">SWC-120</a>
```

**Comment by nbanmp** [comment]
:rage: This is because of eslint trying to be helpful, and assuming that someone would only report eslint issues. We need to edit the eslint html template to use the correct url.

**Comment by nbanmp** [comment]
This is fixed in the version on master! A new release will likely be out in a couple days.
