### ISSUE TITLE
False positive SWC-129 warning

### ISSUE THREAD

**Issue by elenadimitrova** [ConsenSys/truffle-security#223]
`reputationChange = userChildReputationValue * -1;`
produces a SWC-129 warning aUnary operation directly after an assignment`

Although if we invert the multiplication the warning disappears.

See https://github.com/JoinColony/colonyNetwork/pull/623/commits/bb9e31dd8a1b723c8639533aeeb527a2c6d770eb

**Comment by jbroudou** [comment]
The following statement is also producing this false positive

`test1 = -1;`

**Comment by nbanmp** [comment]
This should be resolved - I was unable to reproduce it anymore myself. If not, please complain and I will reopen this.
