### ISSUE TITLE
eslint 6.0.1 incompatible

### ISSUE THREAD

**Issue by celeduc** [ConsenSys/truffle-security#228]
Using truffle-security with eslint 6.0.1 causes the following error when attempting to use `truffle run verify`:
```
> truffle run verify
style is not a valid eslint formatter.
```
Downgrading to eslint 5.16.0 resolves this error.

Note: this error happens whether a truffle-security.json file is present or not.

**Comment by danielrea** [comment]
We now use 5.16.0 by default.
