### ISSUE TITLE
Running in Free mode

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/truffle-security#230]
**Expected behaviour:** If I have my MythX credentials in my shell env, I get the "Premium Analysis"

**Actual behaviour:** When the tool runs, it says I'm in "Free Mode". 

```
$ echo $MYTHX_ETH_ADDRESS
0x[redacted]

$ echo $MYTHX_PASSWORD
[redacted]

$ npx truffle run verify
Welcome to MythX! You are currently running in Free mode.
```

Does this mean I'm getting weaker analysis?

**Comment by nbanmp** [comment]
Sorry for the super late response!

Your credentials seem to only be correlated with a Free account.

The modes are `Trial` (no username/password), `Free` (Non-paying account), and `Premium/Pro` (Paid account). Free mode has limitations compared to the paid account, but during the beta, the only limitation is rate limiting.

You can see what the plan limitations will be when the beta is over here: https://mythx.io/plans
