### ISSUE TITLE
Error: Cannot find module 'truffle-error'

### ISSUE THREAD

**Issue by gpersoon** [ConsenSys/truffle-security#236]
The first time I run "truffle run verify" I got the error:
Error: Cannot find module 'truffle-error'

Solved by: npm install -g truffle-error

Environment: windows 10, node 10.16.3

**Comment by danielrea** [comment]
Hi gpersoon, 

This will be fixed shortly in the next version. Thanks.

**Comment by troggy** [comment]
this issue shouldn't be closed — still not fixed

**Comment by danielrea** [comment]
Thanks for reporting. This should be fixed in 1.6.0. Open this again if you still have issues.
