### ISSUE TITLE
Parse error of JWT login request: No valid username provider (HTTP status 400)

### ISSUE THREAD

**Issue by gpersoon** [ConsenSys/truffle-security#237]
When running truffle run verify with the environment variables
```JS
set MYTHX_ETH_ADDRESS=0x... 
set MYTHX_PASSWORD=
```
I got the error message: Parse error of JWT login request: No valid username provider (HTTP status 400)
After checking I noticed I  had a trailing space at the MYTHX_ETH_ADDRESS, which was causing the problem.

Environment: Windows 10, node: 10.16.3

**Comment by danielrea** [comment]
I will provide more descriptive errors with next version. Thanks for the submission
