### ISSUE TITLE
Parse error of JWT login request: Wrong credentials - check your username and password (HTTP status 400)

### ISSUE THREAD

**Issue by gpersoon** [ConsenSys/truffle-security#238]
I tried to follow the instructions at
https://docs.mythx.io/en/latest/tools/truffle/index.html#accounts-and-access

```JS
Windows:
set MYTHX_ETH_ADDRESS=0x1234567891235678900000000000000000000000
set MYTHX_PASSWORD='Put your password in here!'
```

And setup my password as:
```JS
set MYTHX_PASSWORD='..#..?..'
```

Then I got the error: Parse error of JWT login request: Wrong credentials - check your username and password (HTTP status 400)

I turns out the quotes (')  have to be removed  (e.g. the documentation is misleading)

Environment: windows 10, node 10.16.3

**Comment by danielrea** [comment]
Hi gpersoon, Thank you I have requested the relevant documentation change.
