### ISSUE TITLE
Unexpected Error occured. return value of analyze should be either 0 or 1

### ISSUE THREAD

**Issue by thec00n** [ConsenSys/truffle-security#243]
## Description 
I am running the latest truffle security and every contract analysis seems to throw the following error message `Unexpected Error occured. return value of analyze should be either 0 or 1`

```
truffle-security 1.6.0
api: v1.4.36.12, harvey: 0.0.36, hash: c20260240f10ef42717befc6f43f092a, maru: 0.5.4, mythril: 0.21.14, url: https://api.mythx.io
```

**Comment by danielrea** [comment]
Fixed in v1.6.1
