### ISSUE TITLE
Option to create JSON only results

### ISSUE THREAD

**Issue by thec00n** [ConsenSys/truffle-security#244]
## Description 
As a MythX user I would like to have a command line option the allows me retrieve the results of the analysis in JSON format so that I can post process them. In the current version there is a JSON output option `--style json`. The problem is that if STDOUT is used to fetch the JSON result it will also contain log output from truffle and other places.

## Solution 
Add an option to save the result in JSON format to a file and ensure it is JSON only.

**Comment by area** [comment]
We currently work around this by piping the output: `| grep '^\[{"' > truffle-security-output.json` and then using that file as the input to our post processing.

**Comment by thec00n** [comment]
Thanks @area, nice work around. 

Having an inbuilt option to return JSON only output is still something worth considering.

**Comment by danielrea** [comment]
Try adding --no-mythx-logs with version 1.6.2 and reopen if you have any issues.
