### ISSUE TITLE
 ParserError: Source "ВXuffle__NotFound.sol" not found: Callback not supported.

### ISSUE THREAD

**Issue by Eknir** [ConsenSys/truffle-security#252]
I get the following error when running `truffle run verify`:

```
CompileError: /home/rinke/Projects/rds-contracts/contracts/ContentManagerI.sol:12:1: ParserError: Source "ВXuffle__NotFound.sol" not found: Callback not supported.
import '__Truffle__NotFound.sol';
```

My environment:
`solc version 6.1`
`truffle-security version 1.6.2`

contract directory:
```
PinningManager.sol
Migrations.sol
ContentManager.sol
/vendor/SafeMath.sol
```
All contracts are with `pragma solidity ^0.6.1;`

If I delete the file ContentManagerI.sol, I get still an error:
```
CompileError: /home/rinke/Projects/rds-contracts/contracts/PinningManager.sol:3:1: ParserError: Source "yXe/rinke/Projects/rds-contracts/contracts/vendor/SafeMath.sol" not found: Callback not supported.
import "./vendor/SafeMath.sol";
```

Just running `truffle compile` works without problems

**Comment by krzysu** [comment]
I have the same issue when verifying with truffle with solidity configured to 0.6.2 but works fine with my truffle's default version - solidity 0.5.16.

Truffle version: 5.1.9

truffle-config.js

```
compilers: {
  solc: {
    version: "0.6.2"
  }
}   
```
