### ISSUE TITLE
Submit Solidity standard ASTs (Legacy and Compact)

### ISSUE THREAD

**Issue by thec00n** [ConsenSys/truffle-security#68]
Currently truffle-security submits truffle flavoured ASTs that are incompatible with tools that process standard Solidity ASTs:

- Imports are handled differently in truffle flavoured ASTs. Solidity standard compile artifacts provide `sources` and for each source it generates independent Legacy and Compact AST objects. Each source file has a SourceUnit at the root and as children contracts, pragmas and import directives and so on. truffle ASTs have a single SourceUnit. 
- Some of the attribute values are missing or different. I have not looked extensively but there are definitely differences in regards to node values.

I propose to replace truffle favoured ASTs and send `sources` that contain Solidity standard ASTs.

**Comment by rocky** [comment]
Gerhard avows:

> * Imports are handled differently in truffle flavoured ASTs. Solidity standard compile artifacts provide sources` and for each source it generates independent Legacy and Compact AST objects. Each source file has a SourceUnit at the root and as children contracts, pragmas and import directives and so on. truffle ASTs have a single SourceUnit.
> * Some of the attribute values are missing or different. I have not looked extensively but there are definitely differences in regards to node values.

I would be grateful if you would go into detail so the we can fully see what the difference is. Perhaps create a gist of the difference like did for https://gist.github.com/rocky/f7ac558aa7b4b4eaff0743c7f8bbc9d4 ? 

With details, we are also in a better position to getting this addressed in truffle itself where this would be a much better fix for everybody.

**Comment by rocky** [comment]
This was done a while ago. Not exactly sure how you get "compact", but if that's not done, open a new issue narrowing what remains.
